import math
import sys
import os
CURRENT_DIR = os.path.dirname(os.path.abspath(__file__))

# Add project root to Python path
PROJECT_ROOT = os.path.abspath(
    os.path.join(os.path.dirname(__file__), "..", "..")
)
sys.path.append(PROJECT_ROOT)

import config as cfg

# =====================================================
# DERIVED VALUES
# =====================================================

loiter_time = cfg.LOITER_TIME   # seconds

# =====================================================
# EMPTY WEIGHT CALCULATION (Raymer)
# =====================================================
We = cfg.A * (cfg.MTOW  ** cfg.B)
empty_weight_fraction = We / cfg.MTOW 

# =====================================================
# TSFC CONVERSION
# =====================================================
c = (cfg.TSFC * cfg.G) / 3600   # 1/s

# =====================================================
# CRUISE FUEL FRACTION (Breguet – Jet)
# =====================================================
cruise_fraction = math.exp(
    -(cfg.CRUISE_RANGE * c) / (cfg.CRUISE_SPEED * cfg.L_OVER_D)
)

# =====================================================
# LOITER FUEL FRACTION (Breguet Endurance – Jet)
# =====================================================
loiter_fraction = math.exp(
    -(loiter_time * c) / cfg.L_OVER_D
)

# =====================================================
# TOTAL MISSION WEIGHT FRACTION (NO RESERVE)
# =====================================================
mission_weight_fraction = (
    cfg.WARMUP_TAKEOFF *
    cfg.CLIMB *
    cruise_fraction *
    loiter_fraction *
    cfg.DESCENT * cfg.LANDING
)

# =====================================================
# FUEL WEIGHT (MISSION + RESERVE)
# =====================================================
mission_fuel_fraction = 1 - mission_weight_fraction
mission_fuel_weight = mission_fuel_fraction * cfg.MTOW 

reserve_fuel_weight = mission_fuel_weight * cfg.reserve_fraction
total_fuel_weight = mission_fuel_weight + reserve_fuel_weight
total_fuel_fraction = total_fuel_weight / cfg.MTOW 

# =====================================================
# PAYLOAD WEIGHT
# =====================================================
payload_weight = cfg.MTOW  - (We + total_fuel_weight)

# =====================================================
# OUTPUT
# =====================================================
print("\nJET UAV PRELIMINARY WEIGHT SIZING (CONFIG-DRIVEN)")
print("=================================================")

print("\n--- INPUT (FROM config.py) ---")
print(f"MTOW (W0)                        : {cfg.MTOW :.2f} kg")
print(f"Cruise Range                     : {cfg.CRUISE_RANGE/1000:.1f} km")
print(f"Cruise Speed                     : {cfg.CRUISE_SPEED:.1f} m/s")
print(f"L/D                              : {cfg.L_OVER_D:.1f}")
print(f"Loiter Time                      : {cfg.LOITER_TIME/60} min")
print(f"TSFC                             : {cfg.TSFC:.3f} kg/(N·hr)")
print(f"SFC                              : {c} kg/(N·hr)")
print(f"Reserve Fuel                     : {cfg.reserve_fraction*100:.0f} %")

print("\n--- EMPTY WEIGHT ---")
print(f"Empty Weight (We)                : {We:.2f} kg")
print(f"Empty Weight Fraction            : {empty_weight_fraction:.4f}")

print("\n--- MISSION FUEL ---")
print(f"Cruise Weight Fraction           : {cruise_fraction:.4f}")
print(f"Loiter Weight Fraction           : {loiter_fraction:.4f}")
print(f"Mission Fuel Weight              : {mission_fuel_weight:.2f} kg")

print("\n--- TOTAL FUEL ---")
print(f"Total Fuel Fraction              : {total_fuel_fraction:.4f}")
print(f"Total Fuel Weight                : {total_fuel_weight:.2f} kg")

print("\n--- PAYLOAD ---")
print(f"Payload Weight                   : {payload_weight:.2f} kg")

print("\n--- FEASIBILITY ---")
print("Payload Feasibility              :",
      "✅ POSSIBLE" if payload_weight > 0 else "❌ NOT POSSIBLE")

print("\n=================================================\n")

# =====================================================
# STORE WEIGHTS INSIDE WEIGHT FOLDER
# =====================================================
weights_py = f'''"""
AUTO-GENERATED FILE
DO NOT EDIT MANUALLY
Generated by weight1.py
"""

EMPTY_WEIGHT = {We:.6f}
EMPTY_WEIGHT_FRACTION = {empty_weight_fraction:.6f}

MISSION_FUEL_WEIGHT = {mission_fuel_weight:.6f}
RESERVE_FUEL_WEIGHT = {reserve_fuel_weight:.6f}
TOTAL_FUEL_WEIGHT = {total_fuel_weight:.6f}
TOTAL_FUEL_FRACTION = {total_fuel_fraction:.6f}

PAYLOAD_WEIGHT = {payload_weight:.6f}
'''

weights_py_path = os.path.join(CURRENT_DIR, "weights_output.py")

with open(weights_py_path, "w") as f:
    f.write(weights_py)

print("✅ Weights stored in SUB/weight_estimation/weights_output.py")
